"""add prompt/context metrics columns to trace_metrics

Revision ID: 080454c8164e
Revises: 504ab86a3c3e
Create Date: 2026-08-02 12:12:21.334650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '080454c8164e'
down_revision: Union[str, Sequence[str], None] = '504ab86a3c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trace_metrics', sa.Column('prompt_length_chars', sa.Integer(), nullable=True))
    op.add_column('trace_metrics', sa.Column('context_length_chars', sa.Integer(), nullable=True))
    op.add_column('trace_metrics', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('trace_metrics', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trace_metrics', 'completion_tokens')
    op.drop_column('trace_metrics', 'prompt_tokens')
    op.drop_column('trace_metrics', 'context_length_chars')
    op.drop_column('trace_metrics', 'prompt_length_chars')
    # ### end Alembic commands ###
