"""add latency/cost columns to trace_metrics

Revision ID: c1bb1cc23b12
Revises: 080454c8164e
Create Date: 2026-08-03 11:22:01.442014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1bb1cc23b12'
down_revision: Union[str, Sequence[str], None] = '080454c8164e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trace_metrics', sa.Column('retrieval_latency_ms', sa.Integer(), nullable=True))
    op.add_column('trace_metrics', sa.Column('llm_latency_ms', sa.Integer(), nullable=True))
    op.add_column('trace_metrics', sa.Column('total_latency_ms', sa.Integer(), nullable=True))
    op.add_column('trace_metrics', sa.Column('total_cost_usd', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trace_metrics', 'total_cost_usd')
    op.drop_column('trace_metrics', 'total_latency_ms')
    op.drop_column('trace_metrics', 'llm_latency_ms')
    op.drop_column('trace_metrics', 'retrieval_latency_ms')
    
    # ### end Alembic commands ###
